### ISSUE TITLE
feature request: store all user settings to config.json

### ISSUE THREAD

**Issue by ivysrono** [kaorahi/lizgoban#12]
for example: 
Lizzie style;
set the window to maximize
and so on.

**Comment by kaorahi** [comment]
Lizgoban automatically stores such settings somewhere (~/.config/Electron/lizgoban.json in Linux) and remembers them in the next session. Isn't this enough? Or, is this feature broken in Windows?

**Comment by ivysrono** [comment]
lizgoban.json works. But:
1. merge it and config.json may better to maintain, for users.
2. could not store maximize window settings.
```
  "window": {
    "id0": {
      "board_type": "double_boards",
      "previous_board_type": "suggest",
      "position": [69, -8],
      "size": [1973, 1152]
    }
  },
```
![图片](https://user-images.githubusercontent.com/2649544/59544925-ada27300-8f49-11e9-8ec6-548138a441ec.png)

**Comment by kaorahi** [comment]
For 2., window maximization is now remembered automatically. For 1., I'm afraid that users will be confused if we merge manual settings and automatically stored properties into one common file. They are also separated in Lizzie. I imagine troubles if lizgoban overwrites config.json implicitly.

**Comment by ivysrono** [comment]
Ok, I agree.
So, Could I set these in config.json:
window - maximized
Lizzie style - true
and so on.
By another word, could you support config.json set more(all?) settings that store in lizgoban.json?

**Comment by kaorahi** [comment]
If they can be set in config.json and it has priority over lizgoban.json, we will have merits on copy, backup, and version control of our preferences. But these merits are small practically since we have only a few such settings at present.

I experienced that complicated customization mechanisms made debugging difficult in my past project. So I feel demerits are larger than merits in the present case.

**Comment by ivysrono** [comment]
Thanks.
