### ISSUE TITLE
Can we play with katago？

### ISSUE THREAD

**Issue by ivysrono** [kaorahi/lizgoban#20]
I can't run katago by Sabaki.
Man VS KataGo
Leelaz VS KataGo

**Comment by kaorahi** [comment]
(Human vs. KataGo)
Yes. Would you read "Play against (weakened) leela zero" in "Tips" section in "Help" menu? Please note that time control is not implemented and you need to hit RET key for every turn of the opponent by yourself. I'm not interested in serious/fair matches against engines since they are too strong :)

(Leela Zero vs. KataGo)
No, at present. See #23.

**Comment by ivysrono** [comment]
I have see the Tips, Human VS AI is too cumbersome.

**Comment by kaorahi** [comment]
You only need to hit RET key to play against KataGo. Isn't it simple?

**Comment by ivysrono** [comment]
In my opinion, auto ai play will be more simple.

**Comment by kaorahi** [comment]
I'd like to keep "modeless" UI as far as possible. So I'm not willing to introduce "match mode". See [humane interface](https://en.wikipedia.org/wiki/The_Humane_Interface).
