### ISSUE TITLE
Better presentation of area counts

### ISSUE THREAD

**Issue by kaorahi** [kaorahi/lizgoban#33]
Let's use here for GUI-side discussion about real-time display of area counts https://github.com/lightvector/KataGo/issues/72.

**Comment by kaorahi** [comment]
@lukaszlew: Thx for the idea. 6945595c is a quick test of https://github.com/lightvector/KataGo/issues/72#issuecomment-531586832. Stone sizes are not quantized, though. "X" marks are dead stones.
![by_stone](https://user-images.githubusercontent.com/38910552/64968215-bf930980-d8dc-11e9-87f8-a13e357a156e.png)

**Comment by lukaszlew** [comment]
My intention is to use this feature to train my own wet (brain) neural network :) 
I am routinely counting territories in my games. To have better approximations I include half points sometimes (and I already see from this screenshot I can improve :)). 
I think quantization is useful for the  purpose of a human training to be fast and accurate at it.

I'm also pretty sure that for that points, quarter points are too much. For fast pattern recognition I'd suggest to have half-circles for half-points instead of circles of smaller size.

Also I'm not sure what to do about actual stones being smaller, this is a bit disturbing :)
One idea is to use smaller dots for scoring that could be overlayed atop of the existing stones.

**Comment by kaorahi** [comment]
The shapes of imaginary stones are changed as an alternative to quantization in 029dcfe2 (ownership: 0 < triangle < 1/3 < square < 2/3 < circle <= 1). I'm not sure of nice thresholds.

I don't like this coloring (green / pink) at all. But I cannot find better colors that are easily recognizable.
![overlay](https://user-images.githubusercontent.com/38910552/65042478-dd6f7580-d993-11e9-99cf-32088290186e.png)

**Comment by lukaszlew** [comment]
It is relatively hard for me to practice territory adding in my head now, it is hard to pinpoint why, but 3 symbols and their different sizes seems like too much. 
As for how to visualize, how about circle (with a border so it can be atop of other stones) half of the size of stones? 
Also, consider making your stones a bit smaller so that they barely touch or not touch.

I think it is hard to do territory in my head because square is too similar to circle. Especially when it is big, does not look like a half point.

**Comment by kaorahi** [comment]
Hmm... My purpose of this view is different from yours. I would like to check why KataGo says "17" at the left edge, for example.

In your way, you will count the large font as 1, the medium font as 0.5, and the small (almost invisible) font as 0. Their sum is not 17 but 22. The error is too large for my purpose.

![digits](https://user-images.githubusercontent.com/38910552/65078576-411b9200-d9d8-11e9-8bd6-1d58c996b160.png)

**Comment by lukaszlew** [comment]
Let me start with: X as 10 is hilarious :)

I see, that invariant would be useful for me as well. 
One could dynamically find the thresholds to make it match, i.e.
Select a cluster and sort the intersections according to decrasing probability:
p_i = 0.98 0.86 ... 0.21 0.1 0.01 for i = 1, 2, ...
\sum p_i = 17
Then find two numbers j, k such that 
j * 1 + k * 0.5 = 17
And mark j highest scores with full point and the next k consecutive with a half point (and the rest with zero). j and k could be selected in such a way that mean square error is smallest but there are other ways as well.
This would give different thresholds for each cluster. I wonder whether they would differ much. 

This algorithm effectively moves the rounding errors around to different intersections, but keeping it within a cluster. As a Go-learning tool I think that's feasible to mimic for a human. (human errors are much bigger, that's what pros often comment on with "reading is easy, judgement is hard")

**Comment by kaorahi** [comment]
Sorry. I won't implement it now. I'm not sure whether it is preferred by many users...

But thx for your suggestions. They are useful hints for me.

**Comment by lukaszlew** [comment]
That's fine, I have no expectations :)
