### ISSUE TITLE
Is there any plan to support themes?

### ISSUE THREAD

**Issue by isty2e** [kaorahi/lizgoban#43]
I had used LizGoban for months, and in terms of features LizGoban more satisfactory. However, the major reason I have returned to Lizzie was the visuals. LizGoban is currently not very visually pleasing for me, and sometimes it is hard to read necessary numbers, especially with the default color scheme. Is there any plan to support themes or detailed configuration of visualization?

**Comment by kaorahi** [comment]
Thanks for letting me know it. :)

We need a better default style before themes or personal configurations at present. I don't like the current coloring at all. But I cannot find better colors that are easily recognizable. Can anybody help this project?

If someone is willing to improve the graphic design, I will gather color codes of various items into one place (style.js?) so that they can be modified conveniently.

(I never use "Lizzie style" in "View" menu by myself and do not notice problems of it until issues are posted here.)

**Comment by isty2e** [comment]
Just noticed your commits. It seems to be working without problems, and it is more visually pleasing than before (well, at least for me). Here are the images I am using:
[external.zip](https://github.com/kaorahi/lizgoban/files/4382534/external.zip)
Stone images are from photorealistic theme of Sabaki and the board image is the kaya board image from OGS.
