### ISSUE TITLE
Toggling ownership with KataGo & etc.

### ISSUE THREAD

**Issue by isty2e** [kaorahi/lizgoban#47]
The analyzer at `engine.js:67` is fixed to `kata-analyze ownership true`. Can `ownership true` be removed when endstate estimation is turned off? This can reduce lagging at high visits significantly. 

And can score be displayed somewhere on the screen? It is shown only when hovering over a specific move. When `ownership true` is there, it is next to the visit count on the top of the board, but it is gone when `ownership true` is deleted.

**Comment by kaorahi** [comment]
Done. :)

BTW, I am not sure which is suitable for the score estimation of the current board.

* (A) weighted sum of "scoreMean"s of suggested moves (weighted by their visits)
* (B) "scoreMean" of the best move (= order 0)
* (C) others

Expecting robustness, I use (A) in lizgoban at present. But it tends to be pessimistic due to bad moves in suggestions, as you can observe them on the winrate bar at the bottom of the main board. Do you have any thoughts?

**Comment by isty2e** [comment]
Thanks a lot for the fix!

I think (A) is technically correct, as it is for winrate. (B) will be usually optimistic, since it is a weighted average of values from leaf nodes of the best move. However I'm not that against using (B) for both winrate and score.

**Comment by kaorahi** [comment]
thx for helpful comments. Please close this issue if 1a4959cc works well.
