### ISSUE TITLE
Request: Ability to show grid coordinates all the time

### ISSUE THREAD

**Issue by JamesMowery** [kaorahi/lizgoban#69]
Just a request to have an option to enable the display of coordinates all the time. Some Twitch Go streamers I watch use LizGoban for analysis and also for playing against KataGo. Would be nice to be able to refer to coordinates. I know you can press C to temporarily show them, but just an option under the View menu to always show would be great!

**Comment by kaorahi** [comment]
thx for the proposal! But I'd like to keep such preferences as small as possible in lizgoban for the following reason. If there are other users who also like this feature, please post comments here to alter my policy in this case.

(reason)
In my past project, I implemented almost all user requests. Then I noticed that such preferences (or options, switches, modes, ...) make user-support difficult. I needed to find out numbers of settings for every user who reported any issue. Preferences also cause bugs that appear only in specific combinations and such bugs are often overlooked by the developers.

**Comment by JamesMowery** [comment]
Definitely. But let me ask you this. Have you ever used a Goban program that didn't feature the coordinates display options? It seems to be an extremely basic function that nearly every program has.

More importantly, a program focused on learning I believe should have these options at a minimum. Considering this is already implemented by holding down the "C" key, you've already done the heavy lifting to add this option (as I'm sure you realized having coordinates is a bare necessity). Just asking you add a toggle on the view menu to keep it permanent so other people can actually rely on this program and can interact with it easier. 👍

**Comment by kaorahi** [comment]
Thanks for your kind explanation. I may have overlooked its importance since coordinates are seldom used in Japanese textbooks and lectures. You say it is critical for communication by text/video chat?

There are three reasons why I hesitate to implement it.

1. Additional features tend to make my software buggy if I never use them for myself.
2. I'm trying to keep "modelessness" (cf. [the humane interface](https://en.wikipedia.org/wiki/The_Humane_Interface#Design_rules)) in addition to "undoability" and "no are-you-sure dialog" in lizgoban.
3. We need to redesign the board display. I've already used its border spaces for various messages so that I can save the screen area and show the main board as large as possible. (You want to keep the coordinates even when you are watching the principal variations by mouse-hover on suggested moves, don't you?)

But this issue may be an exception of 1 and 2 if it is so important. I'll reconsider...

**Comment by JamesMowery** [comment]
Fully respect it. Actually, then this is probably more of a Western thing then! So that's good to know.

I think the last bit of input I'd just add here in support of this. If I want to share a screenshot, post on reddit, share an image on Discord, create a YouTube video, or do a live stream and use LizGoban and just ask people why did KataGo make that move... or ask others where they might recommend that we move next. It's just a challenge with the current setup without having the coordinates shown. It makes learning together a bit more of a challenge. Whereas if it's just yourself, I don't think the coordinates are needed either.

I think of LizGoban as an incredible learning tool. And if there's students who are all gathered around using the program or something of that nature, having points to reference is massively helpful. Just noticed this on a Twitch stream when someone asked about coordinates, and it was very frustrating to communicate what moves the other person was recommending without the coordinates available.

Either way, really love the tool and hope you continue developing it further. I feel like LizGoban could easily overtake KaTrain and other popular learning tools in time!

**Comment by kaorahi** [comment]
You have successfully persuaded me (9ce5560c2). :)
Do you have any advice to this screenshot?

![coord](https://user-images.githubusercontent.com/38910552/124771713-52031200-df76-11eb-88a1-9d9cfdb86cf3.png)

BTW, can I ask why you don't use Lizzie or KaTrain? They are much more beautiful and they also have all-in-one packages like LizGoban. https://github.com/featurecat/lizzie/issues/886

**Comment by kaorahi** [comment]
released as 0.6.3
