### ISSUE TITLE
What's the difference between a lizzie-like Go GUI and a non lizzie-like Go GUI?

### ISSUE THREAD

**Issue by HackYardo** [kaorahi/lizgoban#73]
I want to ask the problem because they run differently on my computer.

**Comment by kaorahi** [comment]
(ref. #72)

I close this issue as I cannot help you here:

* The question is still unclear for me. You gave too little information to get a useful answer. (Your post lacks concrete description of "they", "differently", and "my computer" in addition to the configurations of the GUIs and the engines.)
* Even if they are given, I do not have sufficient experience and knowledge to answer such a question.
* Anyway, this does not seem to be an issue of lizgoban.

**Comment by HackYardo** [comment]
@kaorahi The issue should be in Lizzie repo, but it is not in developing this year. The issue is quit easy and can be stated syllogistically:
- The Lizgoban is a Lizzie style Go GUI,;
- You are the developer;
- So you know what does "Lizzie style" mean in programming aspect...

If you don't know, that's regretful. Lizgoban has many original features, but I can't use any Lizzie style Go GUI at a skin temperature...

**Comment by kaorahi** [comment]
If you want to solve your problem, would you show sufficient and concrete information?

You compared Lizzie type GUIs (X, for example) and non-Lizzie type GUIs (Y, for example). Your PC was very hot for X and not so hot for Y. So you want to know the reason of the difference. Right?

Then you should explicitly show the following points at least:

* What are X and Y? (ex. X = Lizzie, Y = Go Review Partner)
* What engines and networks (also called as weights or models) are used for X and Y?
* What configurations are used for X and Y?
* What are your OS and hardware?

I suspect that you may have used a less powerful engine, a smaller network, or smaller playouts for Y. Anyway, I recommend you to ask the question elsewhere with the above four points.

Unfortunately, this issue is not easy for me. It needs too much efforts (writing such interview sheets in a foreign language, studying Y that I have never used, ...). So you cannot expect much of me.

**Comment by HackYardo** [comment]
@kaorahi Thank you a lot. It seems that Lizzie takes real-time Go position/kifu analyzing as its center and many features/configurations surrendering the center, e.g. CPU threads more than [one](https://github.com/featurecat/lizzie/issues/481#issuecomment-455939628), more MCT search depth, `ponder` must turning on to do anything and infinite playouts. And other Lizzie-ish Go GUIs inherit the center. Finally, it does. Just limit threads to 2, it can cool down CPU and never cook dishes again.
